# Generated by Django 5.2.8 on 2025-11-06 11:28

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Body',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kuzov', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Кузов машины',
                'verbose_name_plural': 'Кузова машин',
            },
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=300, verbose_name='Вопрос')),
                ('answer', ckeditor.fields.RichTextField(verbose_name='Ответ')),
            ],
            options={
                'verbose_name': 'Часто задаваемый вопрос',
                'verbose_name_plural': 'Часто задаваемые вопросы',
            },
        ),
        migrations.CreateModel(
            name='Marka',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marka', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Марка машины',
                'verbose_name_plural': 'Марки машин',
            },
        ),
        migrations.CreateModel(
            name='Onboarding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('description', models.CharField(max_length=200, verbose_name='Описание')),
                ('image', models.ImageField(upload_to='onboarding/', verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Онбординг',
                'verbose_name_plural': 'Онбординги',
            },
        ),
        migrations.CreateModel(
            name='SupportMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=200, verbose_name='Тема')),
                ('message', models.TextField(verbose_name='Сообщение')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Сообщение в поддержку',
                'verbose_name_plural': 'Сообщения в поддержку',
            },
        ),
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=100)),
                ('marka', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='models', to='api.marka')),
            ],
            options={
                'verbose_name': 'Модель машины',
                'verbose_name_plural': 'Модели машин',
            },
        ),
    ]
