# Generated by Django 5.2.7 on 2025-11-03 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Onboarding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('description', models.CharField(max_length=200, verbose_name='Описание')),
                ('image', models.ImageField(upload_to='onboarding/', verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Онбординг',
                'verbose_name_plural': 'Онбординги',
            },
        ),
    ]
