# Generated by Django 5.2.7 on 2025-11-03 12:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Body',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kuzov', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Кузов машины',
                'verbose_name_plural': 'Кузова машин',
            },
        ),
        migrations.CreateModel(
            name='Marka',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marka', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Марка машины',
                'verbose_name_plural': 'Марки машин',
            },
        ),
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=100)),
                ('marka', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='models', to='mycar.marka')),
            ],
            options={
                'verbose_name': 'Модель машины',
                'verbose_name_plural': 'Модели машин',
            },
        ),
    ]
