# Generated by Django 5.2.7 on 2025-11-03 12:35

import django.contrib.gis.db.models.fields
import django.db.models.deletion
import phonenumber_field.modelfields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('moyka', models.IntegerField(default=0, verbose_name='Количество мойок')),
                ('unlimited_carwash', models.BooleanField(default=False, verbose_name='Неограниченное количество мойок')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('currency', models.CharField(max_length=10, verbose_name='Валюта')),
                ('title', models.CharField(max_length=200, verbose_name='Информация')),
                ('title_two', models.CharField(max_length=200, verbose_name='Информация2')),
                ('duration_days', models.IntegerField(default=28, verbose_name='Срок подписки (дней)')),
            ],
        ),
        migrations.CreateModel(
            name='CarWash',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='KG', verbose_name='Телефон')),
                ('address', models.CharField(max_length=255, verbose_name='Адрес')),
                ('open_time', models.TimeField(verbose_name='Время открытия')),
                ('closing_time', models.TimeField(verbose_name='Время закрытия')),
                ('rating', models.FloatField(default=0.0, verbose_name='Рейтинг')),
                ('img', models.ImageField(blank=True, null=True, upload_to='carwash_images/', verbose_name='Изображение')),
                ('whatsapp', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, verbose_name='WhatsApp')),
                ('instagram', models.URLField(blank=True, null=True, verbose_name='Instagram')),
                ('location', django.contrib.gis.db.models.fields.PointField(geography=True, srid=4326, verbose_name='Местоположение')),
            ],
            options={
                'verbose_name': 'Автомойка',
                'verbose_name_plural': 'Автомойки',
                'indexes': [models.Index(fields=['location'], name='reservation_locatio_7c9e59_idx')],
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата')),
                ('time', models.TimeField(verbose_name='Время')),
                ('status', models.CharField(choices=[('new', 'Новое'), ('confirmed', 'Подтверждено'), ('cancelled', 'Отменено')], default='new', max_length=10, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('car_wash', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='reservation.carwash', verbose_name='Автомойка')),
            ],
            options={
                'verbose_name': 'Бронирование',
                'verbose_name_plural': 'Бронирования',
                'unique_together': {('car_wash', 'date', 'time')},
            },
        ),
    ]
