# Generated by Django 5.2.8 on 2025-11-06 11:28

import django.contrib.gis.db.models.fields
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата')),
                ('time', models.TimeField(verbose_name='Время')),
                ('wash_done', models.BooleanField(default=False, verbose_name='Мойка выполнена')),
                ('cancelled', models.BooleanField(default=False, verbose_name='Отменено')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Бронирование',
                'verbose_name_plural': 'Бронирования',
            },
        ),
        migrations.CreateModel(
            name='CarWash',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='KG', verbose_name='Телефон')),
                ('address', models.CharField(max_length=255, verbose_name='Адрес')),
                ('open_time', models.TimeField(verbose_name='Время открытия')),
                ('closing_time', models.TimeField(verbose_name='Время закрытия')),
                ('rating', models.FloatField(default=0.0, verbose_name='Рейтинг')),
                ('img', models.ImageField(blank=True, null=True, upload_to='carwash_images/', verbose_name='Изображение')),
                ('whatsapp', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, verbose_name='WhatsApp')),
                ('instagram', models.URLField(blank=True, null=True, verbose_name='Instagram')),
                ('location', django.contrib.gis.db.models.fields.PointField(geography=True, srid=4326, verbose_name='Местоположение')),
            ],
            options={
                'verbose_name': 'Автомойка',
                'verbose_name_plural': 'Автомойки',
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('moyka', models.IntegerField(default=0, verbose_name='Количество моек')),
                ('unlimited_carwash', models.BooleanField(default=False, verbose_name='Неограниченное количество мойок')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('currency', models.CharField(max_length=10, verbose_name='Валюта')),
                ('title', models.CharField(max_length=200, verbose_name='Информация')),
                ('title_two', models.CharField(max_length=200, verbose_name='Информация 2')),
                ('duration_days', models.IntegerField(default=28, verbose_name='Срок подписки (дней)')),
            ],
            options={
                'verbose_name': 'Подписка',
                'verbose_name_plural': 'Подписки',
            },
        ),
        migrations.CreateModel(
            name='UserSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(editable=False, verbose_name='Дата начала')),
                ('end_date', models.DateField(editable=False, verbose_name='Дата окончания')),
                ('payment_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='ID платежа')),
                ('used_washes', models.IntegerField(default=0, verbose_name='Использовано моек')),
            ],
            options={
                'verbose_name': 'Подписка пользователя',
                'verbose_name_plural': 'Подписки пользователей',
            },
        ),
    ]
