# Generated by Django 5.2.7 on 2025-11-03 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0002_alter_subscription_options_alter_subscription_moyka_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersubscription',
            name='end_date',
            field=models.DateField(editable=False, verbose_name='Дата окончания'),
        ),
        migrations.AlterField(
            model_name='usersubscription',
            name='start_date',
            field=models.DateField(editable=False, verbose_name='Дата начала'),
        ),
    ]
