# Generated by Django 5.2.7 on 2025-11-03 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0003_alter_usersubscription_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='title_two',
            field=models.CharField(max_length=200, verbose_name='Информация 2'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='unlimited_carwash',
            field=models.BooleanField(default=False, verbose_name='Неограниченное количество моек'),
        ),
    ]
