# Generated by Django 5.2.7 on 2025-11-03 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0004_alter_subscription_title_two_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='status',
        ),
        migrations.AddField(
            model_name='booking',
            name='wash_done',
            field=models.BooleanField(default=False, verbose_name='Мойка выполнена'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='unlimited_carwash',
            field=models.BooleanField(default=False, verbose_name='Неограниченное количество мойок'),
        ),
    ]
