# Generated by Django 5.2.7 on 2025-11-04 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0005_remove_booking_status_booking_wash_done_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='cancelled',
            field=models.BooleanField(default=False, verbose_name='Отменено'),
        ),
    ]
